### ISSUE TITLE
bullfrog agent Unsupported class file major version 55

### ISSUE THREAD

**Issue by YakirShriker** [thefreebit/bullfrog#8]
artifactory version: 6.16 on k8s.
when starting an agent got this errors in logs:

`020-01-14 10:29:24.215 INFO  org.glowroot - Java version: 11.0.2
2020-01-14 10:29:24.718 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving java/lang/Thread: Unsupported class file major version 55
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:184)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformJava9(WeavingClassFileTransformer.java:77)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.glowroot.agent.init.AgentModule.<init>(AgentModule.java:212)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit.init(NonEmbeddedGlowrootAgentInit.java:103)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:274)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
2020-01-14 10:29:24.747 ERROR o.g.a.w.WeavingClassFileTransformer - error weaving java/lang/management/ManagementFactory: Unsupported class file major version 55
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
	at org.glowroot.agent.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
	at org.glowroot.agent.weaving.Weaver.weaveUnderTimer(Weaver.java:184)
	at org.glowroot.agent.weaving.Weaver.weave(Weaver.java:149)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformInternal(WeavingClassFileTransformer.java:117)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java:94)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transformJava9(WeavingClassFileTransformer.java:77)
	at org.glowroot.agent.weaving.WeavingClassFileTransformer.transform(WeavingClassFileTransformer.java)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at org.glowroot.agent.init.AgentModule.<init>(AgentModule.java:221)
	at org.glowroot.agent.init.NonEmbeddedGlowrootAgentInit.init(NonEmbeddedGlowrootAgentInit.java:103)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:274)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)`

**Comment by YakirShriker** [comment]
Please maintain the client, glowroot released a new version that works with Java 11 as Artifactory 6.16 does.
